[package]
name = "frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
backend = { workspace = true }
bevy_ecs = "0.15.3"
clap = { version = "4.5.31", features = ["derive"] }
lalrpop-util = { version = "0.22.1", features = ["lexer"] }

[build-dependencies]
lalrpop = "0.22.1"
